-- CreateTable
CREATE TABLE `Message` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `MessageID` BIGINT NOT NULL,
    `UserID` BIGINT NOT NULL,
    `ChannelID` BIGINT NOT NULL,
    `GuildID` BIGINT NOT NULL,
    `Timestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Content` TEXT NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
