-- AlterTable
ALTER TABLE `Message` MODIFY `MessageID` VARCHAR(191) NOT NULL,
    MODIFY `UserID` VARCHAR(191) NOT NULL,
    MODIFY `ChannelID` VARCHAR(191) NOT NULL,
    MODIFY `GuildID` VARCHAR(191) NOT NULL;
