require("module-alias/register");
const fs = require("fs");
const path = require("path");
const changelog = require("@root/changelogs.json");

/**
 * Formats the date string to a readable format.
 * @param {string} dateString - The date string to format.
 * @returns {string} The formatted date string.
 */
const formatDate = (dateString) => {
    const options = { year: "numeric", month: "long", day: "numeric" };
    return new Date(dateString).toLocaleDateString(undefined, options);
};

// Initialize the markdown content
let markdownContent = "# Changelog\n\n> This file is automatically generated from the changelogs.json file, using ./utils/helpers/createChangelogMD.js\n\n";

// Reverse the order of changelog entries for most recent first
changelog.reverse().forEach(entry => {
    markdownContent += `## [${entry.version}] - ${formatDate(entry.date)}\n\n`;
    entry.changes.forEach(change => {
        // Check if the change contains a suppressed link
        const suppressedLinkRegex = /<https?:\/\/[^>]+>/g;
        const formattedChange = change.replaceAll(">", "\\>").replace(suppressedLinkRegex, match => match.replaceAll("\\>", ">"));
        markdownContent += `- ${formattedChange}\n`;
    });
    markdownContent += "\n";
});

// Write the markdown content to CHANGELOG.md (overwrite if exists)
const outputPath = path.join(process.cwd(), "CHANGELOG.md");
fs.writeFileSync(outputPath, markdownContent, "utf-8");

console.log("CHANGELOG.md file created successfully.");