require("module-alias/register");
const fs = require("fs");
const path = require("path");
const changelog = require("@root/changelogs.json");
const packageJson = require("@root/package.json");

/**
 * Formats the date string to a readable format.
 * @param {string} dateString - The date string to format.
 * @returns {string} The formatted date string.
 */
const formatDate = (dateString) => {
    const options = { year: "numeric", month: "long", day: "numeric" };
    return new Date(dateString).toLocaleDateString(undefined, options);
};

let markdownContent = "# Changelog\n\n> This file is automatically generated from the changelogs.json file, using ./utils/helpers/createChangelogMD.js\n\n";

const latestChangelogEntry = changelog[changelog.length - 1];

if (!latestChangelogEntry || latestChangelogEntry.version !== packageJson.version) {
    console.error(`Version mismatch: package.json is ${packageJson.version}, but latest changelog entry is ${latestChangelogEntry?.version || "missing"}.`);
    process.exit(1);
}

[...changelog].reverse().forEach(entry => {
    markdownContent += `## [${entry.version}] - ${formatDate(entry.date)}\n\n`;
    entry.changes.forEach(change => {
        const suppressedLinkRegex = /<https?:\/\/[^>]+>/g;
        const formattedChange = change.replaceAll(">", "\\>").replace(suppressedLinkRegex, match => match.replaceAll("\\>", ">"));
        markdownContent += `- ${formattedChange}\n`;
    });
    markdownContent += "\n";
});

const outputPath = path.join(process.cwd(), "CHANGELOG.md");
fs.writeFileSync(outputPath, markdownContent, "utf-8");

console.log("CHANGELOG.md file created successfully.");