name: build nodejs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - production
    paths:
      - Docker/**
jobs:
  push:
    name: "yolks:nodejs_20"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nodejs
          file: ./Docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/itsmaat/discord_bot:nodejs_20